$:.unshift File.expand_path("../lib", __FILE__)

require 'rubygems'
require 'rake'
require 'PROJECT_NAME'

# Runs all tests
require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

namespace :deploy do
    
  desc "Commits changes to local git repo and then pushes to remote"
  task :git do
    git_actions
  end
    
  desc "Builds gemspec and deploys gem to RubyGems.org"
  task :gem do
    rubygems_actions
  end
  
end

namespace :bump do
  
  desc "Bumps major version number by 1"
  task :major do
    PROJECT_NAME_CLASS.bump_version_major
    git_actions
    rubygems_actions
  end

  desc "Bumps minor version number by 1"
  task :minor do
    PROJECT_NAME_CLASS.bump_version_minor
    git_actions
    rubygems_actions
  end

  desc "Bumps patch version number by 1"
  task :patch do
    PROJECT_NAME_CLASS.bump_version_patch
    git_actions
    rubygems_actions
  end
  
end

task :version do
  puts "\nPROJECT_NAME_CLASS Version: #{PROJECT_NAME_CLASS::VERSION}"
end

def git_actions
  Dir.chdir("#{PROJECT_NAME_CLASS::ROOT_PATH}")
  system "git add ."
  system "git commit -v -a -m 'commit for version: #{PROJECT_NAME_CLASS.version}'"
  system "git tag #{PROJECT_NAME_CLASS.version}"
  system "git push"
  system "git push --tags"
end

def rubygems_actions
  Dir.chdir("#{PROJECT_NAME_CLASS::ROOT_PATH}")
  system "gem build PROJECT_NAME.gemspec"
  system "gem push PROJECT_NAME-#{PROJECT_NAME_CLASS.version}.gem"      
end
